### ISSUE TITLE
Response's attempt should be optional

### ISSUE THREAD

**Issue by andrew-gardener** [IMSGlobal/caliper-python#147]
https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html#response

currently it is set to required https://github.com/IMSGlobal/caliper-python/blob/master/caliper/entities.py#L582

**Comment by ViktorHaag** [comment]
Fixed and merged into `master` and `develop`. Will leave this issue open until a new tag and release is cut for `master`.

**Comment by andrew-gardener** [comment]
Thanks for tackling it so quickly!

**Comment by ViktorHaag** [comment]
Closed as bundled in [release 1.1.0.1](https://github.com/IMSGlobal/caliper-python/releases/tag/1.1.0.1).
