### ISSUE TITLE
Frame's index property should be optional

### ISSUE THREAD

**Issue by andrew-gardener** [IMSGlobal/caliper-python#212]
https://github.com/IMSGlobal/caliper-python/blob/master/caliper/entities.py#L341
https://github.com/IMSGlobal/caliper-python/blob/develop/caliper/entities.py#L392

https://github.com/IMSGlobal/caliper-spec/blob/master/caliper-spec.md#frame
https://raw.githack.com/IMSGlobal/caliper-spec/develop/caliper-spec-v1p2.html#Frame

**Comment by ViktorHaag** [comment]
Addressed with PR#213
